### ISSUE TITLE
Error when trying to install python environment

### ISSUE THREAD

**Issue by tasosdsavvidis** [ricds/DL_RS_GEE#2]
Hi Ricardo,

When I try to install the python environment with these lines of code:
rgee::ee_install_set_pyenv(
  py_path = rgee_environment_dir, # Change it for your own Python PATH
  py_env = "rgee_py" # Change it for your own Python ENV
)

I get an error : "Error in ee_clean_pyenv(home) : The directory E: does not exist!"

Nevertheless, the earthengine-api is installed correctly.

Would appreciate any advice, as I am a beginner to this. 
Thank you in advance. :)

**Comment by ricds** [comment]
hi @tasosdsavvidis, i cannot be of much help here, its an issue with rgee installation, I heard the new version solved the installation issues and it should be asier to install with ee_install() now
